const bookmarkItems = [
  'brianlovin.com',
  'rauno.me',
  'chia.design',
  'cretu.dev',
  // 'sdrn.co',
  // 'musing.vercel.app',
  // 'timlrx.com',
  // 'vyshnav.xyz',
  'iamrob.in',
  'neal.fun',
  'karinasirqueira.com',
  'uxdesign.cc/responsive-grids-and-how-to-actually-use-them-970de4c16e01',
  'essays.uxdesign.cc/case-study-factory',
  'blog.tubikstudio.com/color-in-design-influence-on-users-actions',
  'free-for.dev',
  'invisionapp.com/enterprise/design-genome',
  'uxdesign.cc/ux-design-methods-deliverables-657f54ce3c7d',
  'cantunsee.space/',
  // 'sprungstudios.com/2021/10/04/ui-ux-designer-skills-games/',
  'nngroup.com/articles/which-ux-research-methods/',
  'blog.reedsy.com/guide/story-structure/dan-harmon-story-circle/',
  'blog.maximeheckel.com/posts/framer-motion-layout-animations/',
  'bootcamp.uxdesign.cc/how-to-create-a-compelling-design-portfolio-companies-will-notice-b0629fe84ca',
  'a11yproject.com/checklist/',
  'teachyourselfcs.com',
  'tech-stack.tools/',
  'publicapis.dev/',
  'github.com/aniftyco/awesome-tailwindcss',
  'roadmap.sh',
  'keynotopia.com/how-to-create-animated-whiteboard-explainer-videos-for-free-using-apple-keynote/',
]

export default bookmarkItems
