const bookmarkItems = [
  'brianlovin.com',
  'rauno.me',
  'chia.design',
  'timlrx.com',
  'karinasirqueira.com',
  'uxdesign.cc/responsive-grids-and-how-to-actually-use-them-970de4c16e01',
  'essays.uxdesign.cc/case-study-factory',
  'blog.tubikstudio.com/color-in-design-influence-on-users-actions',
  'free-for.dev',
  'uxdesign.cc/ux-design-methods-deliverables-657f54ce3c7d',
  'cantunsee.space',
  'nngroup.com/articles/which-ux-research-methods',
  'blog.reedsy.com/guide/story-structure/dan-harmon-story-circle',
  'blog.maximeheckel.com/posts/framer-motion-layout-animations',
  'bootcamp.uxdesign.cc/how-to-create-a-compelling-design-portfolio-companies-will-notice-b0629fe84ca',
  'a11yproject.com/checklist/',
  'teachyourselfcs.com',
  'publicapis.dev',
  'github.com/aniftyco/awesome-tailwindcss',
  'roadmap.sh',
  'keynotopia.com/how-to-create-animated-whiteboard-explainer-videos-for-free-using-apple-keynote',
  'seungmee-lee.com',
  'nevflynn.com',
  'anarodrigues.design',
  'mattrothenberg.com',
  'blush.design',
  'indiehackers.com',
  'ui.shadcn.com',
  'tailwindcss.com/showcase',
  'blot.im',
  'hiring.cafe',
  'mcmaster.com',
]

export default bookmarkItems
